- hosts: all
  become: yes
  gather_facts: false

  pre_tasks:
    - name: Ensure python3-apt exists (first-run safety on fresh Ubuntu)
      raw: test -e /usr/lib/python3/dist-packages/apt || (apt-get update -y && apt-get install -y python3-apt)
      changed_when: false

    - name: Update apt cache (1h)
      apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:
    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
        state: present

    - name: Remove Apache default index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Deploy a simple PHP page
      copy:
        dest: /var/www/html/index.php
        content: |
          <?php phpinfo(); ?>
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes
